---

- name:             Create EC2 Server
  ec2:
    key_name:         "{{ aws_key_name }}"
    instance_type:    t2.micro
    image:            {{ aws_docker_ami }}
    wait:             yes
    count:            1
    vpc_subnet_id:    "{{ public_subnet_id }}"
    assign_public_ip: yes
  register: docker_ec2

- name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    with_items: "{{ docker_ec2.instances }}"

- name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ docker_ec2.instances }}"




