---

# Load Balancer

- name:               Create Load Balancer Security Group
  ec2_group:
    name:             "Load Balancer"
    #tags:                              # Not Supported
    #  Name: "name"
    description:      "Port 80, 443"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    profile:          "{{ aws_profile }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    state:            "present"
  register: my_lb_group

- name:               Set Load Balancer Security Group ID in variable
  set_fact:
    lb_group_id: "{{ my_lb_group.group_id }}"

- name:               Create Load Balancer
  ec2_elb_lb:
    name:             "webapp"
    state:            "present"
    profile:          "{{ aws_profile }}"
    region:           "{{ aws_region }}"
    security_group_ids: "{{ lb_group_id }}"
    instance_ids:
      - "{{ item.id }}"
    subnets:
      - "{{ private_subnet_az1_id }}"
      - "{{ private_subnet_az2_id }}"
    listeners:
      - protocol:             tcp
        load_balancer_port:   80
        instance_port:        80
        proxy_protocol:       true
      - protocol:             tcp
        load_balancer_port:   443
        instance_port:        443
        proxy_protocol:       true
    health_check:
      ping_protocol:        https
      ping_port:            443
      ping_path:            "/ping"
      response_timeout:     5
      interval:             30
      unhealthy_threshold:  2
      healthy_threshold:    10
  with_flattened:
    - "{{ webapp_az1_ec2s.tagged_instances }}"
    - "{{ webapp_az2_ec2s.tagged_instances }}"
